### ISSUE TITLE
.net core 3.0 System.NotSupportedException

### ISSUE THREAD

**Issue by jstzwhc** [autofac/Autofac#1029]
System.NotSupportedException
  HResult=0x80131515
  Message=ConfigureServices returning an System.IServiceProvider isn't supported.
  Source=Microsoft.AspNetCore.Hosting
  StackTrace:
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()

**Comment by Ap0k** [comment]
Show the initialization code (Programm.cs and Startup.cs files)

**Comment by tillig** [comment]
[Also, be sure to read the docs.](https://autofac.readthedocs.io/en/latest/integration/aspnetcore.html#asp-net-core-3-0-and-generic-hosting)

**Comment by jstzwhc** [comment]
in program.cs
I lost .UseServiceProviderFactory(new AutofacServiceProviderFactory())

**Comment by tillig** [comment]
Sounds like you figured it out.
