### ISSUE TITLE
InvalidProgramException on netcore3

### ISSUE THREAD

**Issue by springy76** [autofac/Autofac#1039]
I cross compiled some code targeting netcore3 which runs fine on net48 (and did unchanged on net47x in the past).

Now I get this exception:

```
Autofac.Core.DependencyResolutionException
  HResult=0x80131500
  Message=An exception was thrown while activating ClassA -> λ:ClassBFactory.
  Source=Autofac
  StackTrace:
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Resolving.InstanceLookup.<>c__DisplayClass6_0.<Execute>b__0()
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)

Inner Exception 1:
InvalidProgramException: Cannot create boxed ByRef-like values.
```

The problem is caused by a readonly-ref struct I used for passing parameters -- and the problem goes away when removing the `ref` modifier:

```
public delegate ClassB ClassBFactory(ClassBSetup setup);

public readonly ref struct ClassBSetup { /*...*/ }
```

All classes use constructor-injection: `ClassA` acquires `ClassBFactory` and `ClassB` acquires `ClassBSetup `.

Version used: 4.9.4 (and 4.9.2)

**Comment by nblumhardt** [comment]
Hi! I think it's likely that the exception on .NET Core is correctly diagnosing a problem that the older .NET Framework runtime is unaware of.

Since Autofac works via reflection, it's unlikely that it will be easily extended to handle `ref` structs, which are incompatible with reflection in some fundamental ways.

In the long run, some kind of IL emit here could possibly work around it, but there's substantial effort involved in finding/implementing that kind of solution (should be a very interesting problem to tackle, though!)

For now, your best bet is removing the `ref` modifier.
