### ISSUE TITLE
Exception with Autofac 5.0.0 and Interception

### ISSUE THREAD

**Issue by LucidObscurity** [autofac/Autofac#1075]
```
Autofac.Core.DependencyResolutionException: An exception was thrown while executing a resolve operation. See the InnerException for details. ---> Castle.DynamicProxy.ProxyGenerationException: This is a DynamicProxy2 error: Target type for the proxy implements Castle.DynamicProxy.IProxyTargetAccessor which is a DynamicProxy infrastructure interface and you should never implement it yourself. Are you trying to proxy an existing proxy?
   at Castle.DynamicProxy.Generators.BaseProxyGenerator.HandleExplicitlyPassedProxyTargetAccessor(ICollection`1 targetInterfaces, ICollection`1 additionalInterfaces)
   at Castle.DynamicProxy.Generators.InterfaceProxyWithTargetGenerator.GetTypeImplementerMapping(Type[] interfaces, Type proxyTargetType, IEnumerable`1& contributors, INamingScope namingScope)
   at Castle.DynamicProxy.Generators.InterfaceProxyWithTargetGenerator.GenerateType(String typeName, Type proxyTargetType, Type[] interfaces, INamingScope namingScope)
   at Castle.DynamicProxy.Generators.InterfaceProxyWithTargetGenerator.<>c__DisplayClass6_0.<GenerateCode>b__0(String n, INamingScope s)
   at Castle.Core.Internal.SynchronizedDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Castle.DynamicProxy.Generators.BaseProxyGenerator.ObtainProxyType(CacheKey cacheKey, Func`3 factory)
   at Castle.DynamicProxy.ProxyGenerator.CreateInterfaceProxyWithTarget(Type interfaceToProxy, Type[] additionalInterfacesToProxy, Object target, ProxyGenerationOptions options, IInterceptor[] interceptors)
   at Autofac.Extras.DynamicProxy.RegistrationExtensions.<>c__DisplayClass9_0`3.<EnableInterfaceInterceptors>b__0(Object sender, ActivatingEventArgs`1 e)
   at Autofac.Core.Registration.ComponentRegistration.RaiseActivating(IComponentContext context, IEnumerable`1 parameters, Object& instance)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at TestConsole.Program.Main(String[] args) in C:\Dev\Keith\TestAutofac\TestConsole\TestConsole\Program.cs:line 28
```
Reproduction:
```
using System;
using Autofac;
using Autofac.Extras.DynamicProxy;
using Castle.DynamicProxy;

namespace TestConsole
{
    public interface IRepoTest { int Get(); }
    public class RepoTest : IRepoTest { public int Get() => 1; }
    public class InterceptorTest : IInterceptor { public void Intercept(IInvocation invocation) { invocation.Proceed(); invocation.ReturnValue = (int)invocation.ReturnValue + 1; } }
    class Program
    {
        static void Main(string[] args)
        {
            var builderTest = new ContainerBuilder();

            builderTest.RegisterType<RepoTest>()
                .As<IRepoTest>()
                .EnableInterfaceInterceptors()
                .InterceptedBy(typeof(InterceptorTest));

            builderTest.Register(c => new InterceptorTest());

            var containerTest = builderTest.Build();

            try
            {
                var repo = containerTest.Resolve<IRepoTest>();

                Console.WriteLine(repo.Get());
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
            }

            Console.ReadLine();
        }
    }
}
```
Project File:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="5.0.0" />
    <PackageReference Include="Autofac.Extras.DynamicProxy" Version="4.5.0" />
    <PackageReference Include="Castle.Core" Version="4.4.0" />
  </ItemGroup>

</Project>
```
**NOTE:** downgrading Autofac to 4.9.4 resolves the issue. I've also tried the minimum version required by Autofac.Extras.DynamicProxy (4.0.1) which also works.

**Comment by tillig** [comment]
This is an issue with the Autofac.Extras.DynamicProxy extension, not Autofac core. [As noted in the Autofac 5 release notes](https://github.com/autofac/Autofac/releases/tag/v5.0.0), we're still working on updating the integration and extension libraries.

Please be patient, we're getting there. If you still see it after you get the updated version of Autofac.Extras.Moq [once it's released] then file a new issue. Thanks!

**Comment by LucidObscurity** [comment]
Thanks @tillig. Sorry for not reading the release notes...I'm just starting the switch from Unity so was unaware of the current state of things here.
