### ISSUE TITLE
Can't resolve named service in delegate factory (service register the decorator)

### ISSUE THREAD

**Issue by rzlink** [autofac/Autofac#1197]
## Describe the Bug

1. Register component with named services;
2. Register the decorator for the service;
3. Register delegate factory to resolve named serviced.

Call delegate factory throw exception:
_**DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'TestAutofac+TaskDecorator' can be invoked with the available services and parameters:
Cannot resolve parameter 'ITask taskDecoratee' of constructor 'Void .ctor(ITask)'.**_

## Steps to Reproduce

```c#
[TestClass]
public class TestAutofac
{
    public interface ITask
    {
        void Run();
    }

    public delegate ITask TaskLocator(string name);

    public class TaskB : ITask
    {
        public void Run()
        {
            Trace.TraceInformation("TaskB");
        }
    }

    public class TaskA : ITask
    {
        public void Run()
        {
            Trace.TraceInformation("TaskA");
        }
    }

    public class TaskDecorator : ITask
    {
        private readonly ITask taskDecoratee;

        public TaskDecorator(ITask taskDecoratee)
        {
            this.taskDecoratee = taskDecoratee;
        }

        public void Run()
        {
            Trace.TraceInformation("TaskDecorator");

            taskDecoratee.Run();
        }
    }

    [TestMethod]
    public void TestAutofacDecorator()
    {
        var builder = new ContainerBuilder();
        builder.RegisterType<TaskA>().Named<ITask>("A");
        builder.RegisterType<TaskB>().Named<ITask>("B");
        builder.RegisterDecorator<TaskDecorator, ITask>();
        builder.Register<TaskLocator>(
            c =>
                {
                    var ctx = c.Resolve<IComponentContext>();
                    return taskName => ctx.ResolveNamed<ITask>(taskName);
                });

        var container = builder.Build();

        using (var scope = container.BeginLifetimeScope())
        {
            var taskLocator = scope.Resolve<TaskLocator>();

            // This will throw exception
            var task = taskLocator.Invoke("A");
            task.Run();

            Assert.IsInstanceOfType(task, typeof(TaskDecorator));
        }
    }
}
```

## Exception with Stack Trace

```text
Put the exception with stack trace here.

Test method TestAutofac.TestAutofacDecorator threw exception: 
Autofac.Core.DependencyResolutionException: An exception was thrown while activating TestAutofac+TaskDecorator. ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'TestAutofac+TaskDecorator' can be invoked with the available services and parameters:
Cannot resolve parameter 'ITask taskDecoratee' of constructor 'Void .ctor(ITask)'.
    at Autofac.Core.Activators.Reflection.ReflectionActivator.GetValidConstructorBindings(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
--- End of inner exception stack trace ---
    at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at lambda_method(Closure , String )
   at TestAutofac.TestAutofacDecorator() in D:\Test\TestAutofac.cs:line 73
```

## Dependency Versions

Autofac: 

Autofac: 5.2.0

**Comment by tillig** [comment]
I just ran this test using an upcoming v6 package - `6.0.0-develop-01132` - and the test passes. So whatever was going wrong in v5 has been rectified by the (fairly major) internals changes that will be coming soon in v6.

There is no plan to fix issues in v5 at this time; we're pushing hard to a v6 release soon and the fix will be there. Given that, I'm going to close this issue as already fixed.
