### ISSUE TITLE
System.MissingMethodException: Method not found:

### ISSUE THREAD

**Issue by sonsy-soft** [autofac/Autofac#1212]
I upgrade Autofac to version 6 
and Autofac.Extentions.DependencInjection to 7.0.2

then I get this exception 

System.MissingMethodException: Method not found: 'Void Autofac.Core.IComponentRegistration.add_Preparing(System.EventHandler`1<Autofac.Core.PreparingEventArgs>)'.
   at AutofacSerilogIntegration.ContextualLoggingModule.AttachToComponentRegistration(IComponentRegistryBuilder componentRegistry, IComponentRegistration registration)
   at Autofac.Module.<AttachToRegistrations>b__4_0(Object sender, ComponentRegisteredEventArgs e)
   at Autofac.Core.Registration.ComponentRegistryBuilder.add_Registered(EventHandler`1 value)
   at Autofac.Module.AttachToRegistrations(IComponentRegistryBuilder componentRegistry)
   at Autofac.Module.Configure(IComponentRegistryBuilder componentRegistry)
   at Autofac.ContainerBuilder.Build(IComponentRegistryBuilder componentRegistry, Boolean excludeDefaultModules)
   at Autofac.ContainerBuilder.Build(ContainerBuildOptions options)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProviderFactory.CreateServiceProvider(ContainerBuilder containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at WebUI.Program.Main(String[] args) in D:\WebUI\Program.cs:line 27

I use .net core 3.1 , what's wrong with my code?

**Comment by tillig** [comment]
By taking the major release of Autofac.Extensions. DependencyInjection you also took the major upgrade to Autofac. [Lifetime scope events like OnPreparing are changed in Autofac v6. Check out the release notes.](https://github.com/autofac/Autofac/releases/tag/v6.0.0)
