### ISSUE TITLE
RegisterModule does not work properly on net5

### ISSUE THREAD

**Issue by exy3351** [autofac/Autofac#1258]
When using json configuration file injection, autofac throws an exception

at Autofac.Configuration.Core.ConfigurationExtensions.GetType(IConfiguration configuration, String key, Assembly defaultAssembly)
   at Autofac.Configuration.Core.ComponentRegistrar.RegisterConfiguredComponents(ContainerBuilder builder, IConfiguration configuration)
   at Autofac.Configuration.Core.ConfigurationRegistrar.RegisterConfiguration(ContainerBuilder builder, IConfiguration configuration)
   at Autofac.Configuration.ConfigurationModule.Load(ContainerBuilder builder)
   at Autofac.Module.Configure(IComponentRegistryBuilder componentRegistry)
   at Autofac.ContainerBuilder.Build(IComponentRegistryBuilder componentRegistry, Boolean excludeDefaultModules)
   at Autofac.ContainerBuilder.Build(ContainerBuildOptions options)

See the attachment for the demo reproduced

[AutofacDemo.zip](https://github.com/autofac/Autofac/files/6040758/AutofacDemo.zip)

**Comment by tillig** [comment]
Wrong repo, moving.
