### ISSUE TITLE
在.net5中无法通过json配置文件注入对象

### ISSUE THREAD

**Issue by exy3351** [autofac/Autofac#1259]
## 测试代码

```c#
static class Program
    {
        [STAThread]
        static void Main()
        {            
            try
            {
                AutofacContainer fac = new AutofacContainer();

                var p = $@"{Application.StartupPath}Autofac.json";
                fac.RegisterConfig(p);
                fac.Build();

                var demo = fac.Resolve<IDemo>();
                var value = demo?.GetValue();
                Console.WriteLine(value);
            }
            catch (Exception exception)
            {
                Console.WriteLine(exception);
            }
        }

    }

public class AutofacContainer
    {

        private readonly ContainerBuilder _builder = new ContainerBuilder();

        private IContainer _container;

        public virtual void Build()
        {
            _container = _builder.Build();
        }

        public virtual void RegisterConfig(string fullName)
        {
            if (string.IsNullOrWhiteSpace(fullName)) return;
            var config = (fullName.Trim().ToLower().EndsWith(".json")
                    ? new ConfigurationBuilder().AddJsonFile(fullName)
                    : new ConfigurationBuilder().AddXmlFile(fullName))
                .Build();

            var configModule = new ConfigurationModule(config);
            _builder.RegisterModule(configModule);
        }

        public virtual T Resolve<T>()
        {
            return _container.Resolve<T>();
        }
    }
```

## 异常消息

The type 'DemoLib.Demo1, DemoLib' could not be found. It may require assembly qualification, e.g. "MyType, 
MyAssembly".

## Exception with Stack Trace
```text
at Autofac.Configuration.Core.ConfigurationExtensions.GetType(IConfiguration configuration, String key, Assembly defaultAssembly)
   at Autofac.Configuration.Core.ComponentRegistrar.RegisterConfiguredComponents(ContainerBuilder builder, IConfiguration configuration)
   at Autofac.Configuration.Core.ConfigurationRegistrar.RegisterConfiguration(ContainerBuilder builder, IConfiguration configuration)
   at Autofac.Configuration.ConfigurationModule.Load(ContainerBuilder builder)
   at Autofac.Module.Configure(IComponentRegistryBuilder componentRegistry)
   at Autofac.ContainerBuilder.Build(IComponentRegistryBuilder componentRegistry, Boolean excludeDefaultModules)
   at Autofac.ContainerBuilder.Build(ContainerBuildOptions options)
   at DemoCore.AutofacContainer.Build() in D:\Developer\AutofacDemo\DemoCore\AutofacContainer.cs:line 21
   at AutofacDemo.Form1.button1_Click(Object sender, EventArgs e) in D:\Developer\AutofacDemo\AutofacDemo\Form1.cs:line 30
```

## Dependency Versions

<PackageReference Include="Autofac" Version="6.1.0" />
	  <PackageReference Include="Autofac.Configuration" Version="6.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Configuration" Version="5.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="5.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="5.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Xml" Version="5.0.0" />
	  <PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions" Version="5.0.0" />

## 可重现的Demo
附件中有完整的测试Demo
[AutofacDemo.zip](https://github.com/autofac/Autofac/files/6046913/AutofacDemo.zip)

**Comment by tillig** [comment]
Duplicate autofac/Autofac.Configuration#36
