### ISSUE TITLE
Delegate factory with parameter name 'value' throws

### ISSUE THREAD

**Issue by msv2017** [autofac/Autofac#1275]
## Describe the Bug

Delegate factory throws on instance activation when it has parameter with name `value`

## Steps to Reproduce

```c#
public interface ISomeService { }
public class SomeService : ISomeService { }

public class MyComponent
{
    public ISomeService Service { get; set; }
    public delegate MyComponent Factory(string value);

    public MyComponent(string value)
    {
    }
}

public class ReproTest
{
    [Fact]
    public void Test()
    {
        // Arrange
        var builder = new ContainerBuilder();
        builder.RegisterType<SomeService>().As<ISomeService>();
        builder.RegisterType<MyComponent>().PropertiesAutowired();
        var container = builder.Build();

        // Act
        var factory = container.Resolve<MyComponent.Factory>();

        // Assert
        Assert.NotNull(factory("Autofac is great!"));
    }
}

```

## Expected Behavior

Delegate factory should produce properly activated component with `Service` property resolved.

## Exception with Stack Trace

Autofac.Core.DependencyResolutionException : An exception was thrown while activating UnitTests.MyComponent.
---- System.InvalidCastException : Unable to cast object of type 'System.String' to type 'UnitTests.ISomeService'.

## Dependency Versions

Autofac: 6.2.0

## Additional Info

What I've tried so far:
- changing delegate factory parameter name to something else fixed the issue
- changing parameter type to other type (e.g. string, object) without changing the name still throws

So, to work around the issue, delegate factory should not have parameter with name `value`.

**Comment by tillig** [comment]
I am able to reproduce the issue using the above code.

The full exception with stack trace is:

```text
Autofac.Core.DependencyResolutionException: An exception was thrown while activating AutofacRepro.UnitTest1+MyComponent.
 ---> System.InvalidCastException: Unable to cast object of type 'System.String' to type 'ISomeService'.
   at Autofac.Core.Activators.Reflection.AutowiringPropertyInjector.CallPropertySetter[TDeclaringType,TValue](Action`2 setter, Object target, Object value)
   at Autofac.Core.Activators.Reflection.AutowiringPropertyInjector.InjectProperties(IComponentContext context, Object instance, IPropertySelector propertySelector, IEnumerable`1 parameters)
   at Autofac.Builder.RegistrationBuilder`3.<>c__DisplayClass41_0.<PropertiesAutowired>b__0(ResolveRequestContext ctxt, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DelegateMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.RegistrationPipelineInvokeMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at lambda_method(Closure , String )
   at AutofacRepro.UnitTest1.Repro() in /Users/tillig/dev/autofac/_Repro/UnitTest1.cs:line 24
```

The exception source is actually in the property injector, and, sure enough, if you remove `PropertiesAutowired` then the name `value` doesn't matter at all. So there's something weird in the interaction of delegate factories and the property injection thing that is causing an issue.

Which makes a little more sense, as `value` is a reserved word when it comes to property getter/setter terminology.
