### ISSUE TITLE
Unable to resolve correct instance of service registered in two different scopes

### ISSUE THREAD

**Issue by mihailpw** [autofac/Autofac#1373]
## Describe the Bug

If you register two implementations for different scopes, it won't be able to resolve the correct service from a particular scope.
It happens because [DefaultRegisteredServicesTracker.cs#L185](https://github.com/autofac/Autofac/blob/1910177140fb7da375b6b554e5c31c71a3fb38e4/src/Autofac/Core/Registration/DefaultRegisteredServicesTracker.cs#L185) doesn't really check the scope in which the instance was requested and takes last registered service.

## Steps to Reproduce

```c#
public class Tests
{
  [Fact]
  public void Resolve_RegisterTwoTypesForOneInterfaceForDifferentLifetimeScopes_ResolvesCorrectInstance()
  {
    var builder = new ContainerBuilder();
    builder.RegisterType<Class1>().As<IInterface>().InstancePerMatchingLifetimeScope(nameof(Class1));
    builder.RegisterType<Class2>().As<IInterface>().InstancePerMatchingLifetimeScope(nameof(Class2));
    var container = builder.Build();

    using var scope = container.BeginLifetimeScope(nameof(Class1));
    var instance = scope.Resolve<IInterface>();

    Assert.That(instance, Is.TypeOf<Class1>());
  }
}

interface IInterface { }
class Class1 : IInterface { }
class Class2 : IInterface { }
```

## Expected Behavior

`instance` is type of `Class1`

## Exception with Stack Trace

```text
Autofac.Core.DependencyResolutionException: Unable to resolve the type 'Tests.Class2' because the lifetime scope it belongs in can't be located. The following services are exposed by this registration:
-Tests.IInterface

Details
 ---> Autofac.Core.DependencyResolutionException: No scope with a tag matching 'Class2' is visible from the scope in which the instance was requested.

If you see this during execution of a web application, it generally indicates that a component registered as per-HTTP request is being requested by a SingleInstance() component (or a similar scenario). Under the web integration always request dependencies from the dependency resolver or the request lifetime scope, never from the container itself.

See https://autofac.rtfd.io/help/no-matching-scope for more info.
   at Autofac.Core.Lifetime.MatchingScopeLifetime.FindScope(ISharingLifetimeScope mostNestedVisibleScope)
   at Autofac.Core.Resolving.Middleware.ScopeSelectionMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ScopeSelectionMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext ctxt)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext ctxt)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context)
   at Tests.Tests.Resolve_RegisterTwoTypesForOneInterfaceForDifferentLifetimeScopes_ResolvesCorrectInstance()
```

## Dependency Versions

Autofac: 7.0.0

**Comment by tillig** [comment]
[From the documentation](https://autofac.readthedocs.io/en/latest/troubleshooting/exceptions/no-scope-with-matching-tag.html)

> If you register some components with a matching lifetime scope and some without it can cause problems. For example, say you register one `IMyService` as a singleton and then register a second `IMyService` as `InstancePerMatchingLifetimeScope`. If you try to resolve `IEnumerable<IMyService>` outside a matching lifetime scope, you’ll get an error. Even though one of the `IMyService` could be resolved, not all of them can. `InstancePerMatchingLifetimeScope` is not a filter to allow an instance to sometimes be resolved.

Same thing here - `InstancePerMatchingLifetimeScope` is not a filter, but you're trying to use it like that.
