### ISSUE TITLE
Problem Registering Internal Dispatcher with Autofac in Orleans Integration

### ISSUE THREAD

**Issue by kabaogluemre** [autofac/Autofac#1436]
## Describe the Bug

I’m integrating Orleans with Autofac as the IoC container and encountering issues when attempting to register the internal Orleans.Runtime.Dispatcher class in Autofac. This issue has occured while upgrading Autofac from 4.9.4 to 8.1.1. Previously, the setup worked with Autofac 4.9.4, but after the upgrade, the same approach no longer works.
The error is `NoConstructorsFoundException`

```
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Orleans.Hosting.SiloHost -> Orleans.Runtime.Silo.
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Orleans.Runtime.ILocalSiloDetails, System.IServiceProvider)' on type 'Silo'.
 ---> Autofac.Core.Activators.Reflection.NoConstructorsFoundException: No constructors on type 'Orleans.Runtime.Dispatcher' can be found with the constructor finder 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder'.
```

## Steps to Reproduce

Orleans registers Dispatcher using services.TryAddSingleton as shown below:

`services.TryAddSingleton<Dispatcher>(sp => sp.GetRequiredService<Catalog>().Dispatcher);`

The Dispatcher class **has an internal constructor and depends on Catalog, which is also internal**. When I attempt to re-register or resolve Dispatcher on Autofac using reflection or a custom `IConstructorFinder`, it fails.

The following approaches were attempted but did not work:

1. Using Reflection to resolve the Dispatcher instance:
```
builder.Register(context =>
{
    var serviceProvider = context.Resolve<IServiceProvider>();
    var catalog = serviceProvider.GetRequiredService(catalogType);

    var dispatcherProperty = catalogType.GetProperty("Dispatcher", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public);
    if (dispatcherProperty == null)
    {
        throw new InvalidOperationException("Dispatcher property not found on Catalog.");
    }

    return dispatcherProperty.GetValue(catalog);
})
.As(dispatcherType)
.SingleInstance();

```

2. Using a Custom Constructor Finder:
```
builder.RegisterType(dispatcherType)
    .FindConstructorsWith(new AllConstructorFinder())
    .AsSelf()
    .SingleInstance();
```

```
public class AllConstructorFinder : IConstructorFinder
{
    private static readonly ConcurrentDictionary<Type, ConstructorInfo[]> _cache = new ConcurrentDictionary<Type, ConstructorInfo[]>();

    public ConstructorInfo[] FindConstructors(Type targetType)
    {
        var result = _cache.GetOrAdd(targetType, t => t.GetTypeInfo().DeclaredConstructors.Where(c => !c.IsStatic).ToArray());

        return result.Length > 0 ? result : throw new NoConstructorsFoundException(targetType, this);
    }
}
```

Here is the relevant code in my Autofac integration:

```
.UseServiceProviderFactory(
    services =>
    {
        var scope = _container.BeginLifetimeScope(
            builder =>
            {
                var excludedServiceTypes = new[] { "Orleans.Runtime.Dispatcher" };

                bool IsLogger(ServiceDescriptor s) => s.ServiceType == typeof(LoggerFactory) || s.ServiceType == typeof(ILoggerFactory);
                bool IsExcluded(ServiceDescriptor s) => excludedServiceTypes.Contains(s.ServiceType.FullName);

                // Filter original Dispatcher registration
                var filteredServices = services.Where(s => !IsLogger(s) && !IsExcluded(s)).ToList();
                builder.Populate(filteredServices);

                builder.RegisterInstance(new LoggerFilterOptions { MinLevel = LogLevel.Information }).AsSelf();
                builder.RegisterType<LoggerFactory>().As<ILoggerFactory>().UsingConstructor(typeof(IEnumerable<ILoggerProvider>), typeof(LoggerFilterOptions));

                var catalogType = typeof(GrainService).Assembly.GetType("Orleans.Runtime.Catalog");
                var dispatcherType = typeof(GrainService).Assembly.GetType("Orleans.Runtime.Dispatcher");

                if (catalogType != null && dispatcherType != null)
                {
                    builder.Register(context =>
                    {
                        var serviceProvider = context.Resolve<IServiceProvider>();
                        var catalog = serviceProvider.GetRequiredService(catalogType);

                        var dispatcherProperty = catalogType.GetProperty("Dispatcher", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public);
                        if (dispatcherProperty == null)
                        {
                            throw new InvalidOperationException("Dispatcher property not found on Catalog.");
                        }

                        return dispatcherProperty.GetValue(catalog);
                    })
                    .As(dispatcherType)
                    .SingleInstance();
                }
            });

        var serviceProvider = new AutofacServiceProvider(scope);

        // Retrieve my registered Dispatcher type, it is found, no problem
        var components = scope.ComponentRegistry.Registrations.Where(x => x.Services.Any(x => x.Description.Contains("Dispatcher"))).ToList();
        // Resolve ISiloHost for testing purposes which resolves Dispatcher type, it fails here with 'NoConstructorsFoundException'
        var siloHost = serviceProvider.GetRequiredService<ISiloHost>();
        return serviceProvider;
    })
```

So the problem is that Autofac continues to look for the **original registration of Dispatcher (while it is being filtered)**, which results in the same error: `NoConstructorsFoundException`. Despite explicitly registering Dispatcher in the ContainerBuilder using reflection or a custom constructor finder, Autofac appears to ignore these registrations and fails to resolve the type.

Even when we filter out the original Dispatcher registration and do not attempt to re-register it, Autofac still throws the same error. In this case, I was expecting Autofac to indicate "no registration found" instead of attempting to resolve Dispatcher with its internal constructor.

## Exception with Stack Trace

```
An exception was thrown while activating Orleans.Hosting.SiloHost -> Orleans.Runtime.Silo.
An exception was thrown while invoking the constructor 'Void .ctor(Orleans.Runtime.ILocalSiloDetails, System.IServiceProvider)' on type 'Silo'.
No constructors on type 'Orleans.Runtime.Dispatcher' can be found with the constructor finder 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder'.

See https://autofac.rtfd.io/help/no-constructors-found for more info.
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Orleans.Hosting.SiloHost -> Orleans.Runtime.Silo.
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Orleans.Runtime.ILocalSiloDetails, System.IServiceProvider)' on type 'Silo'.
 ---> Autofac.Core.Activators.Reflection.NoConstructorsFoundException: No constructors on type 'Orleans.Runtime.Dispatcher' can be found with the constructor finder 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder'.

See https://autofac.rtfd.io/help/no-constructors-found for more info.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ConfigurePipeline(IComponentRegistryServices componentRegistryServices, IResolvePipelineBuilder pipelineBuilder)
   at Autofac.Core.Registration.ComponentRegistration.BuildResolvePipeline(IComponentRegistryServices registryServices, IResolvePipelineBuilder pipelineBuilder)
   at Autofac.Core.Registration.ComponentRegistration.BuildResolvePipeline(IComponentRegistryServices registryServices)
   at Autofac.Core.Registration.DefaultRegisteredServicesTracker.AddRegistration(IComponentRegistration registration, Boolean preserveDefaults, Boolean originatedFromDynamicSource)
   at Autofac.Core.Registration.DefaultRegisteredServicesTracker.GetInitializedServiceInfo(Service service)
   at Autofac.Core.Registration.DefaultRegisteredServicesTracker.ServiceMiddlewareFor(Service service)
   at Autofac.Core.Registration.ComponentRegistry.ServiceMiddlewareFor(Service service)
   at Autofac.Core.Registration.ExternalRegistryServiceMiddlewareSource.ProvideMiddleware(Service service, IComponentRegistryServices availableServices, IResolvePipelineBuilder pipelineBuilder)
   at Autofac.Core.Registration.DefaultRegisteredServicesTracker.BeginServiceInfoInitialization(Service service, ServiceRegistrationInfo info, IEnumerable`1 registrationSources)
   at Autofac.Core.Registration.DefaultRegisteredServicesTracker.GetInitializedServiceInfo(Service service)
   at Autofac.Core.Registration.DefaultRegisteredServicesTracker.TryGetServiceRegistration(Service service, ServiceRegistration& serviceData)
   at Autofac.Core.Registration.ComponentRegistry.TryGetServiceRegistration(Service service, ServiceRegistration& serviceRegistration)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumercable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Orleans.Runtime.Silo..ctor(ILocalSiloDetails siloDetails, IServiceProvider services)
   at lambda_method577(Closure, Object[])
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<>c__DisplayClass14_0.<UseSingleConstructorActivation>b__0(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DelegateMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Extensions.DependencyInjection.KeyedServiceMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Extensions.DependencyInjection.KeyedServiceMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.RegistrationPipelineInvokeMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.<>c__DisplayClass5_0.<Execute>b__0()
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid id, Func`1 creator)
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid primaryId, Nullable`1 qualifyingId, Func`1 creator)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext context)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest& request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest& request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest& request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest& request)
   at Autofac.Core.Lifetime.LifetimeScope.Autofac.IComponentContext.ResolveComponent(ResolveRequest& request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at SomeApp.Common.Orleans.SomeAppSiloHostBuilder.<>c__DisplayClass5_0.<BuildHost>b__6(IServiceCollection services) in C:\Code\SomeApp_NET8\Source\SomeApp.Common.Orleans\Orleans\SomeAppSiloHostBuilder.cs:line 153
   at Orleans.Hosting.DelegateServiceProviderFactory.CreateServiceProvider(IServiceCollection services)
   at Orleans.Hosting.ServiceProviderFactoryAdapter`1.BuildServiceProvider(HostBuilderContext context, IServiceCollection services)
   at Orleans.Hosting.ServiceProviderBuilder.BuildServiceProvider(HostBuilderContext context)
   at Orleans.Hosting.SiloHostBuilder.CreateServiceProvider()
   at Orleans.Hosting.SiloHostBuilder.Build()
   at SomeApp.Common.Orleans.SomeAppSiloHostBuilder.BuildHost(String clusterName, Action`1 setExtraOptions, Assembly[] grainAssemblies) in C:\Code\SomeApp_NET8\Source\SomeApp.Common.Orleans\Orleans\SomeAppSiloHostBuilder.cs:line 171
   at SomeApp.Common.Orleans.SomeAppSiloHostBuilder.BuildHost(String clusterName, Assembly[] grainAssemblies) in C:\Code\SomeApp_NET8\Source\SomeApp.Common.Orleans\Orleans\SomeAppSiloHostBuilder.cs:line 54
   at SomeApp.Accounting.Reprocessing.Service.ApplicationGuest.OnStarted() in C:\Code\SomeApp_NET8\Source\SomeApp.Accounting.Reprocessing.Service\ApplicationGuest.cs:line 60
   at SomeApp.Core.Services.Host.ServiceHost.ServiceGuestAggregate.<>c.<OnStarted>b__5_0(IServiceGuest g) in C:\Code\SomeApp_NET8\Source\SomeApp.Core\Services\Host\ServiceHost.cs:line 219
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at SomeApp.Core.Services.Host.ServiceHost.ServiceGuestAggregate.OnStarted() in C:\Code\SomeApp_NET8\Source\SomeApp.Core\Services\Host\ServiceHost.cs:line 219
   at SomeApp.Core.Services.Host.ServiceHost.Start() in C:\Code\SomeApp_NET8\Source\SomeApp.Core\Services\Host\ServiceHost.cs:line 97
   at SomeApp.Core.Services.Host.ServiceHost.Start(HostControl hostControl) in C:\Code\SomeApp_NET8\Source\SomeApp.Core\Services\Host\ServiceHost.cs:line 103
   at SomeApp.Core.Services.Host.ServiceHostFactory.<>c__3`1.<Run>b__3_2(T service, HostControl control) in C:\Code\SomeApp_NET8\Source\SomeApp.Core\Services\Host\ServiceHostFactory.cs:line 53
   at Topshelf.Builders.DelegateServiceBuilder`1.DelegateServiceHandle.Start(HostControl hostControl)
   at Topshelf.Hosts.ConsoleRunHost.Run()
An exception was thrown while activating Orleans.Hosting.SiloHost -> Orleans.Runtime.Silo.
An exception was thrown while invoking the constructor 'Void .ctor(Orleans.Runtime.ILocalSiloDetails, System.IServiceProvider)' on type 'Silo'.
No constructors on type 'Orleans.Runtime.Dispatcher' can be found with the constructor finder 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder'.

See https://autofac.rtfd.io/help/no-constructors-found for more info.
Topshelf.Hosts.ConsoleRunHost Error: 0 : An exception occurred, Autofac.Core.DependencyResolutionException: An exception was thrown while activating Orleans.Hosting.SiloHost -> Orleans.Runtime.Silo.
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Orleans.Runtime.ILocalSiloDetails, System.IServiceProvider)' on type 'Silo'.
 ---> Autofac.Core.Activators.Reflection.NoConstructorsFoundException: No constructors on type 'Orleans.Runtime.Dispatcher' can be found with the constructor finder 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder'.

See https://autofac.rtfd.io/help/no-constructors-found for more info.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ConfigurePipeline(IComponentRegistryServices componentRegistryServices, IResolvePipelineBuilder pipelineBuilder)
   at Autofac.Core.Registration.ComponentRegistration.BuildResolvePipeline(IComponentRegistryServices registryServices, IResolvePipelineBuilder pipelineBuilder)
   at Autofac.Core.Registration.ComponentRegistration.BuildResolvePipeline(IComponentRegistryServices registryServices)
   at Autofac.Core.Registration.DefaultRegisteredServicesTracker.AddRegistration(IComponentRegistration registration, Boolean preserveDefaults, Boolean originatedFromDynamicSource)
   at Autofac.Core.Registration.DefaultRegisteredServicesTracker.GetInitializedServiceInfo(Service service)
   at Autofac.Core.Registration.DefaultRegisteredServicesTracker.ServiceMiddlewareFor(Service service)
   at Autofac.Core.Registration.ComponentRegistry.ServiceMiddlewareFor(Service service)
   at Autofac.Core.Registration.ExternalRegistryServiceMiddlewareSource.ProvideMiddleware(Service service, IComponentRegistryServices availableServices, IResolvePipelineBuilder pipelineBuilder)
   at Autofac.Core.Registration.DefaultRegisteredServicesTracker.BeginServiceInfoInitialization(Service service, ServiceRegistrationInfo info, IEnumerable`1 registrationSources)
   at Autofac.Core.Registration.DefaultRegisteredServicesTracker.GetInitializedServiceInfo(Service service)
   at Autofac.Core.Registration.DefaultRegisteredServicesTracker.TryGetServiceRegistration(Service service, ServiceRegistration& serviceData)
   at Autofac.Core.Registration.ComponentRegistry.TryGetServiceRegistration(Service service, ServiceRegistration& serviceRegistration)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Orleans.Runtime.Silo..ctor(ILocalSiloDetails siloDetails, IServiceProvider services)
   at lambda_method577(Closure, Object[])
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.BoundConstructor.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.<>c__DisplayClass14_0.<UseSingleConstructorActivation>b__0(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DelegateMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Extensions.DependencyInjection.KeyedServiceMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Extensions.DependencyInjection.KeyedServiceMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.RegistrationPipelineInvokeMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.<>c__DisplayClass5_0.<Execute>b__0()
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid id, Func`1 creator)
   at Autofac.Core.Lifetime.LifetimeScope.CreateSharedInstance(Guid primaryId, Nullable`1 qualifyingId, Func`1 creator)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Pipeline.ResolvePipelineBuilder.<>c__DisplayClass14_0.<BuildPipeline>b__1(ResolveRequestContext context)
   at Autofac.Core.Pipeline.ResolvePipeline.Invoke(ResolveRequestContext context)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest& request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest& request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest& request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest& request)
   at Autofac.Core.Lifetime.LifetimeScope.Autofac.IComponentContext.ResolveComponent(ResolveRequest& request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at Autofac.Extensions.DependencyInjection.AutofacServiceProvider.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at SomeApp.Common.Orleans.SomeAppSiloHostBuilder.<>c__DisplayClass5_0.<BuildHost>b__6(IServiceCollection services) in C:\Code\SomeApp_NET8\Source\SomeApp.Common.Orleans\Orleans\SomeAppSiloHostBuilder.cs:line 153
   at Orleans.Hosting.DelegateServiceProviderFactory.CreateServiceProvider(IServiceCollection services)
   at Orleans.Hosting.ServiceProviderFactoryAdapter`1.BuildServiceProvider(HostBuilderContext context, IServiceCollection services)
   at Orleans.Hosting.ServiceProviderBuilder.BuildServiceProvider(HostBuilderContext context)
   at Orleans.Hosting.SiloHostBuilder.CreateServiceProvider()
   at Orleans.Hosting.SiloHostBuilder.Build()
   at SomeApp.Common.Orleans.SomeAppSiloHostBuilder.BuildHost(String clusterName, Action`1 setExtraOptions, Assembly[] grainAssemblies) in C:\Code\SomeApp_NET8\Source\SomeApp.Common.Orleans\Orleans\SomeAppSiloHostBuilder.cs:line 171
   at SomeApp.Common.Orleans.SomeAppSiloHostBuilder.BuildHost(String clusterName, Assembly[] grainAssemblies) in C:\Code\SomeApp_NET8\Source\SomeApp.Common.Orleans\Orleans\SomeAppSiloHostBuilder.cs:line 54
   at SomeApp.Accounting.Reprocessing.Service.ApplicationGuest.OnStarted() in C:\Code\SomeApp_NET8\Source\SomeApp.Accounting.Reprocessing.Service\ApplicationGuest.cs:line 60
   at SomeApp.Core.Services.Host.ServiceHost.ServiceGuestAggregate.<>c.<OnStarted>b__5_0(IServiceGuest g) in C:\Code\SomeApp_NET8\Source\SomeApp.Core\Services\Host\ServiceHost.cs:line 219
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at SomeApp.Core.Services.Host.ServiceHost.ServiceGuestAggregate.OnStarted() in C:\Code\SomeApp_NET8\Source\SomeApp.Core\Services\Host\ServiceHost.cs:line 219
   at SomeApp.Core.Services.Host.ServiceHost.Start() in C:\Code\SomeApp_NET8\Source\SomeApp.Core\Services\Host\ServiceHost.cs:line 97
   at SomeApp.Core.Services.Host.ServiceHost.Start(HostControl hostControl) in C:\Code\SomeApp_NET8\Source\SomeApp.Core\Services\Host\ServiceHost.cs:line 103
   at SomeApp.Core.Services.Host.ServiceHostFactory.<>c__3`1.<Run>b__3_2(T service, HostControl control) in C:\Code\SomeApp_NET8\Source\SomeApp.Core\Services\Host\ServiceHostFactory.cs:line 53
   at Topshelf.Builders.DelegateServiceBuilder`1.DelegateServiceHandle.Start(HostControl hostControl)
   at Topshelf.Hosts.ConsoleRunHost.Run()
```

## Dependency Versions

Autofac: 8.1.1 (It behaves same on 7.1.0)

**Comment by tillig** [comment]
I hate to say, but you're upgrading across four new _major versions_ of Autofac, all of which include breaking changes notes in their release notes. This breaking behavior change - where Autofac only looks at _public_ constructors by default - actually ended up, it appears, slipping into [6.2.0](https://github.com/autofac/Autofac/releases/tag/v6.2.0), IIRC, which possibly should have been a major version change but was still _three years ago_ so I'm not going to be too hard on myself for it.

 [If you need to use an internal constructor you can still do it by providing your own constructor selector or specifying a particular constructor to use,](https://autofac.readthedocs.io/en/latest/register/registration.html#specifying-a-constructor) which you saw, but it also looks like you didn't register all the dependencies with the same constructor finder. Everything that has an internal constructor needs to be registered with your custom finder.

In general, "internal thing from some other library" registered in the container to tie to "other internal thing in other library," while supported through all the reflection-and-plugin mechanisms, is going to take some work to get through. It's something you'll probably have to dig into in your app, or the consuming libraries, and fight with.

If you do think it's a bug, we'll need a minimal repro. Not Orleans, but actually:

- One unit test assembly.
- A separate assembly that has two internal types, each with an internal constructor.
- Unit test assembly references type assembly but does not have access to internals.
- Unit test registers both internal types and uses a constructor finder that allows internal constructors to be found. Unit test resolves the first type that takes the second type as a dependency.

If you can get that to work, it's not an Autofac bug. If you can't get that to work, you might need to use the [diagnostics in Autofac](https://autofac.readthedocs.io/en/latest/troubleshooting/diagnostics.html) to verify that things are registered the way you think they are. And if you still can't get it to work, _maybe_ it's a bug. But there's nothing we can really do to jump into a custom app implementing a framework we don't directly support to troubleshoot that app poking into the internals of that framework to try to register things that aren't accessible. Sorry.
