### ISSUE TITLE
Cannot register generic classes which implement two or more interfaces with the same name (but different namespaces)

### ISSUE THREAD

**Issue by richardbladh** [autofac/Autofac#530]
Hi all!

I seem to have found an issue with registration of types that implement interfaces with the same name but different namespaces.

```c#
namespace FluentValidation {
   interface IValidator<T> { }
   class AbstractValidator<T> : FluentValidation.IValidator<T> { }
}

namespace OurCompany {
   interface IValidator<T> { } // Please note that this name is the same as FluentValidation's IValidator<T>
   class CompositeValidator<T> : FluentValidation.AbstractValidator<T>, OurCompany.IValidator<T> { }
}

namespace OurApplication {
   class SomeClass {
      void SomeSetupMethod() {
         autofacBuilder
            .RegisterGeneric(typeof(CompositeValidator<>))
            .As(typeof(OurCompany.IValidator<>)); // This row is the reason for the exception...it doesn't matter if I specify the FluentValidation.IValidator<> either...
      }
   }
}
```

The following exception is raised when I try to update the IoC-container with the registered generics.

An exception of type 'System.InvalidOperationException' occurred in Autofac.dll but was not handled in user code.
Additional information: The type 'CompositeValidator'1' does not implement the interface 'OurCompany.IValidator'1'.

StackTrace:
   at Autofac.Features.OpenGenerics.OpenGenericServiceBinder.GetInterface(Type implementationType, Type serviceType)
   at Autofac.Features.OpenGenerics.OpenGenericServiceBinder.EnforceBindable(Type implementationType, IEnumerable`1 services)
   at Autofac.Features.OpenGenerics.OpenGenericRegistrationSource..ctor(RegistrationData registrationData, ReflectionActivatorData activatorData)
   at Autofac.Features.OpenGenerics.OpenGenericRegistrationExtensions.<>c__DisplayClass1.<RegisterGeneric>b__0(IComponentRegistry cr)
   at Autofac.ContainerBuilder.Build(IComponentRegistry componentRegistry, Boolean excludeDefaultModules)
   at Autofac.ContainerBuilder.Update(IComponentRegistry componentRegistry)
   at Autofac.ContainerBuilder.Update(IContainer container, ContainerBuildOptions options)
   at Autofac.ContainerBuilder.Update(IContainer container)

I am running the latest version as of today (v. 3.3.1).
Could someone solve this issue. My current workaround is to rename on of the interfaces to avoid name-clashes.

Kind regards,
Richard Bladh

**Comment by tillig** [comment]
[It appears we have the exact failing unit test in place](https://github.com/autofac/Autofac/blob/develop/test/Autofac.Test/Features/OpenGenerics/ComplexGenericsTests.cs#L240) right now in core Autofac and it's been passing for some time. The latest version of `OpenGenericServiceBinder` also [compares both name and namespace](https://github.com/autofac/Autofac/blob/develop/src/Autofac/Features/OpenGenerics/OpenGenericServiceBinder.cs#L106).

I'm guessing this got fixed and just never got closed, so I'll go ahead and close it.
