### ISSUE TITLE
RegisterAssemblyModules fail to ignore/skip internal modules with internal constructors

### ISSUE THREAD

**Issue by caioproiete** [autofac/Autofac#748]
In a class library, I have an module that is intended to be registered and used within the class library itself, and should not be used/registered by other assemblies referencing the class library.

If I define the class as `internal`, Autofac registers it anyway (by design, I think).

If I define the constructor of the class also as `internal`, then `RegisterAssemblyModules` fails with an exception (below).

Example:

    internal class MyCustomModule : Module
    {
        internal MyCustomModule()
        {
        }

        protected override void Load(ContainerBuilder builder)
        {
            // ...
        }
    }

Exception when calling `RegisterAssemblyModules`:

    Autofac.Core.DependencyResolutionException: No constructors on type 'CaioProiete.MyCustomModule' can be found with the constructor finder 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder'.
       at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
       at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
       at Autofac.Core.Resolving.InstanceLookup.Execute()
       at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
       at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
       at Autofac.Features.Collections.CollectionRegistrationSource.<>c__DisplayClass4.<>c__DisplayClass6.<RegistrationsFor>b__1(IComponentRegistration cr)
       at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
       at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       at Autofac.Features.Collections.CollectionRegistrationSource.<>c__DisplayClass4.<RegistrationsFor>b__0(IComponentContext c, IEnumerable`1 p)
       at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
       at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
       at Autofac.Core.Resolving.InstanceLookup.Execute()
       at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
       at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
       at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
       at Autofac.Core.Container.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
       at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
       at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
       at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
       at Autofac.ModuleRegistrationExtensions.RegisterAssemblyModules(IModuleRegistrar registrar, Type moduleType, Assembly[] assemblies)
       at Autofac.ModuleRegistrationExtensions.RegisterAssemblyModules[TModule](IModuleRegistrar registrar, Assembly[] assemblies)
       at Autofac.ModuleRegistrationExtensions.RegisterAssemblyModules(ContainerBuilder builder, Assembly[] assemblies)

**Comment by tillig** [comment]
This is pretty functions-as-designed. The default method of constructor location looks specifically for public constructors. Generally that's a good thing and I don't think we'll change the default behavior.

One thing you can do is mark your class constructor public. If the class is already marked internal, leaving the constructor public should still work as intended - you won't see the class outside the assembly, but the Autofac constructor finder will still be able to locate the constructor.

You can see [the meat of the function here](https://github.com/autofac/Autofac/blob/41aa4dd2117c913fd244c2a09186db5867a12bf3/src/Autofac/ModuleRegistrationExtensions.cs#L156) - when using `RegisterAssemblyModules` there's a tiny, temporary `ContainerBuilder` used to try to register all the modules. There's no great way to provide our usual override capabilities for changing the constructor finder used, though if you see a way we'd be happy to look at a pull request.

In the end, though, the easiest solution for you would be to just make the constructor public and leave the class internal.

**Comment by caioproiete** [comment]
Hi @tillig,
Thanks for looking at this.

> In the end, though, the easiest solution for you would be to just make the constructor public and leave the class internal.

That resolves the exception issue, sure, but it doesn't really solve the main issue I'm pointing out, which is to have Autofac **not** register my module at all.

I had to resort to a hack having a public and an internal constructor, just to skip code execution. You can see here: https://github.com/nblumhardt/autofac-serilog-integration/pull/10/files

---

Having a way to tell Autofac not to register some modules is important for people developing libraries that integrates with Autofac and need to control how the module is registered with the container.

I looked at the code and agree there's no great way to provide override capabilities for changing the constructor finder used, but maybe as an alternative approach, we could have an attribute e.g. `[SkipModuleRegistration]` (better name TBD) that we would apply to the modules we don't want to be picked up via assembly registration...

What do you think?

**Comment by tillig** [comment]
I guess I misunderstood what you were asking for. If you were looking for a way to selectively not register a module, it sounds like this is a duplicate of #747 - looking for a way to control module registration when used in conjunction with assembly scanning.

Given that, I'll close this and ideas around how to better handle assembly scanning for modules can be discussed in #747.

**Comment by caioproiete** [comment]
Thanks @tillig.

I think detecting duplicate registration of the same module and marking a module to not be registered, are two different things - and I'd expect two different PR's for that, but OK... I'll add further comments in #747
