### ISSUE TITLE
Is it possible that passing ctor parameters while resolving a registration ?

### ISSUE THREAD

**Issue by osoykan** [autofac/Autofac#805]
Hi,

I don't know which place is gonna be proper for this question/suggestion, but it makes more sense to write here.

So, I have a registered component:

![image](https://cloud.githubusercontent.com/assets/9823085/19581628/1bfc3592-9737-11e6-8112-c091b7b3568f.png)

and i want to resolve this class in runtime;

`IocContainer.Resolve<SampleApplicationDbContext>(new {nameOrConnectionString = "\\SQLExpress.WhateverDatabase"});`

So, i want to decide that which constructor i want in resolving time by passing parameter or parameters to Resolve method. 

In this case, i'm getting "UnableToChooseFromMultipleConstructors" exception. Because the SampleApplicationDbContext has 3 constructors and two of them have same parameter lengths.

I think that if "MostParametersConstructorSelector" operation made based on constructor's parameters Length and Types we somehow can handle this(not sure about that).

I'm sorry, If I couldn't express myself properly.
Any idea appreciated.
Thanks in advance.

Exception Details:

> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = SampleApplicationDbContext (ReflectionActivator), Services = [Stove.TestBase.SampleApplication.EntityFramework.SampleApplicationDbContext, System.Data.Entity.Infrastructure.IObjectContextAdapter, Stove.Dependency.ITransientDependency, Stove.IShouldInitialize], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> Cannot choose between multiple constructors with equal length 1 on type 'Stove.TestBase.SampleApplication.EntityFramework.SampleApplicationDbContext'. Select the constructor explicitly, with the UsingConstructor() configuration method, when the component is registered (See inner exception for details.)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Stove.Dependency.IocManager.Resolve[T](Object argumentsAsAnonymousType) in D:\srcs\GitProjects\Stove\Stove\Dependency\IocManager.cs:line 320
   at Stove.EntityFramework.DefaultDbContextResolver.Resolve[TDbContext](String connectionString) in D:\srcs\GitProjects\Stove\Stove.EntityFramework\EntityFramework\DefaultDbContextResolver.cs:line 23
   at Stove.EntityFramework.Uow.EfUnitOfWork.GetOrCreateDbContext[TDbContext]() in D:\srcs\GitProjects\Stove\Stove.EntityFramework\EntityFramework\Uow\EfUnitOfWork.cs:line 146
   at Stove.EntityFramework.Uow.UnitOfWorkExtensions.GetDbContext[TDbContext](IActiveUnitOfWork unitOfWork) in D:\srcs\GitProjects\Stove\Stove.EntityFramework\EntityFramework\Uow\UnitOfWorkExtensions.cs:line 32
   at Stove.EntityFramework.Uow.UnitOfWorkDbContextProvider`1.GetDbContext() in D:\srcs\GitProjects\Stove\Stove.EntityFramework\EntityFramework\Uow\UnitOfWorkDbContextProvider.cs:line 28
   at Stove.EntityFramework.Repositories.EfRepositoryBase`3.get_Context() in D:\srcs\GitProjects\Stove\Stove.EntityFramework\EntityFramework\Repositories\EfRepositoryBaseOfTEntityAndTPrimaryKey.cs:line 26
   at Stove.EntityFramework.Repositories.EfRepositoryBase`3.get_Table() in D:\srcs\GitProjects\Stove\Stove.EntityFramework\EntityFramework\Repositories\EfRepositoryBaseOfTEntityAndTPrimaryKey.cs:line 31
   at Stove.EntityFramework.Repositories.EfRepositoryBase`3.Insert(TEntity entity) in D:\srcs\GitProjects\Stove\Stove.EntityFramework\EntityFramework\Repositories\EfRepositoryBaseOfTEntityAndTPrimaryKey.cs:line 93
   at Castle.Proxies.Invocations.IRepository`2_Insert.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Stove.Domain.Uow.UnitOfWorkInterceptor.PerformSyncUow(IInvocation invocation, UnitOfWorkOptions options) in D:\srcs\GitProjects\Stove\Stove\Domain\Uow\UnitOfWorkInterceptor.cs:line 68
   at Stove.Domain.Uow.UnitOfWorkInterceptor.PerformUow(IInvocation invocation, UnitOfWorkOptions options) in D:\srcs\GitProjects\Stove\Stove\Domain\Uow\UnitOfWorkInterceptor.cs:line 81
   at Stove.Domain.Uow.UnitOfWorkInterceptor.Intercept(IInvocation invocation) in D:\srcs\GitProjects\Stove\Stove\Domain\Uow\UnitOfWorkInterceptor.cs:line 36
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IRepository`2Proxy.Insert(Message entity)
   at >Stove.TestBase.SampleApplication.Tests.Auditing.AuditedEntity_Tests.Should_Write_Audit_Properties() in D:\srcs\GitProjects\Stove\Stove.TestBase.SampleApplication.Tests\Auditing\AuditedEntity_Tests.cs:line 29

>Autofac.Core.DependencyResolutionException
Cannot choose between multiple constructors with equal length 1 on type 'Stove.TestBase.SampleApplication.EntityFramework.SampleApplicationDbContext'. Select the constructor explicitly, with the UsingConstructor() configuration method, when the component is registered
   at >Stove.Dependency.CustomMostParameterConstructorSelector.SelectConstructorBinding(ConstructorParameterBinding[] constructorBindings) in D:\srcs\GitProjects\Stove\Stove\Dependency\CustomMostParameterConstructorSelector.cs:line 53
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)

**Comment by osoykan** [comment]
Simple test case:

As a result: DelegateFactories doesn't work on multiple constructors with same parameter lenght.

```csharp
public class IocManager_DelegateFactories_Tests : TestBaseWithLocalIocManager
{
    public IocManager_DelegateFactories_Tests()
    {
        LocalIocManager.Register<IAnimal, Human>();
        LocalIocManager.Register<IVagon, Truck>();
    }

    [Fact]
    public void TestCase()
    {
        var factoryBasedResolution = LocalIocManager.IocContainer.Resolve<Func<string, IAnimal>>();

        factoryBasedResolution.Invoke("Oğuzhan").Name.ShouldBe("Oğuzhan");

        var defaultResolution = LocalIocManager.IocContainer.Resolve<IAnimal>(new {name = "Oğuzhan"}.GetTypedResolvingParameters());

        defaultResolution.Name.ShouldBe("Oğuzhan");
    }
}

public interface IAnimal
{
    string Name { get; set; }
}

public interface IVagon {}

public class Truck : IVagon {}

public class Human : IAnimal
{
    private IVagon _vagon;
    public string Name { get; set; }
  

    public Human(string name)
    {
        Name = name;
    }

    public Human(IVagon vagon)
    {
        _vagon = vagon;
    }

}

**Comment by tillig** [comment]
When you register the component [you can tell Autofac which constructor you want to use](http://autofac.readthedocs.io/en/latest/register/registration.html#specifying-a-constructor). If that isn't enough, you could register with lambdas.

Which is to say, instead of relying on reflection, use [a lambda expression registration](http://autofac.readthedocs.io/en/latest/register/registration.html#lambda-expression-components) to add logic to which constructor to use [based on the available parameters](http://autofac.readthedocs.io/en/latest/resolve/parameters.html#parameters-with-lambda-expression-components).

```csharp
builder.Register((c, p) =>
  {
    string connString = null;
    try
    {
      connString = p.Named<string>("nameOrConnectionString");
    }
    catch (InvalidOperationException)
    {
      // Parameter wasn't present.
    }

    if (connString == null)
    {
      return new SampleApplicationDbContext();
    }
    else
    {
      return new SampleApplicationDbContext(connString);
    }
  }).As<SampleApplicationDbContext>();
```

and

```csharp
var context = scope.Resolve<SampleApplicationDbContext>(
  new NamedParameter("nameOrConnectionString", "NameGoesHere");
```

**Comment by osoykan** [comment]
Thanks @tillig, appreciate it.
