### ISSUE TITLE
Fails to resolve dependency in child scope when parent registered with SingleInstance()

### ISSUE THREAD

**Issue by anjdreas** [autofac/Autofac#809]
Using `<package id="Autofac" version="4.2.0" targetFramework="net46" />`

The resolve fails with an exception if I register `Rules` using `SingleInstance()`, and succeeds if not. Is this by design, or a defect? Intuitively to me, this should work for both cases.

Might possibly be related to #801.

```csharp
using System;
using Autofac;
using NUnit.Framework;

namespace MyTests
{
    [TestFixture]
    public class MyTest
    {
        [Test]
        public void Test([Values(true, false)] bool singleInstance)
        {
            var builder = new ContainerBuilder();

            if (singleInstance)
            {
                builder.RegisterType<Rules>()
                    .SingleInstance();
            }
            else
            {
                builder.RegisterType<Rules>();
            }

            builder.RegisterType<RuleRegisteredInRoot>()
                .As<IRule>();

            using (IContainer lsRoot = builder.Build())
            {
                using (ILifetimeScope childScope = lsRoot.BeginLifetimeScope("childScope",
                    b =>
                    {
                        b.RegisterType<DependencyRegisteredInChildScope>();
                    }))
                {
                    var rules = childScope.Resolve<Rules>();
                    Assert.AreEqual(1, rules.AllRules.Length, "Num resolved rules.");
                }
            }
        }

        private class DependencyRegisteredInChildScope {}

        private class RuleRegisteredInRoot : IRule
        {
            public RuleRegisteredInRoot(Func<DependencyRegisteredInChildScope> dep) {}
        }

        private class Rules
        {
            public Rules(IRule[] allRules)
            {
                AllRules = allRules;
            }

            public IRule[] AllRules { get; }
        }

        private interface IRule {}
    }
}
```

Failing test case:
```
Autofac.Core.DependencyResolutionException : An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = Rules (DelegateActivator), Services = [SwingCatalyst.Test.Unit.TempTest+Rules], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = ExternallyOwned ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = Rules (ReflectionActivator), Services = [SwingCatalyst.Test.Unit.TempTest+Rules], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IRule[] (DelegateActivator), Services = [SwingCatalyst.Test.Unit.TempTest+IRule[]], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = ExternallyOwned ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = RuleRegisteredInRoot (ReflectionActivator), Services = [SwingCatalyst.Test.Unit.TempTest+IRule], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'SwingCatalyst.Test.Unit.TempTest+RuleRegisteredInRoot' can be invoked with the available services and parameters:
Cannot resolve parameter 'System.Func`1[SwingCatalyst.Test.Unit.TempTest+DependencyRegisteredInChildScope] dep' of constructor 'Void .ctor(System.Func`1[SwingCatalyst.Test.Unit.TempTest+DependencyRegisteredInChildScope])'. (See inner exception for details.) (See inner exception for details.) (See inner exception for details.) (See inner exception for details.)
  ----> Autofac.Core.DependencyResolutionException : An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = Rules (ReflectionActivator), Services = [SwingCatalyst.Test.Unit.TempTest+Rules], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IRule[] (DelegateActivator), Services = [SwingCatalyst.Test.Unit.TempTest+IRule[]], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = ExternallyOwned ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = RuleRegisteredInRoot (ReflectionActivator), Services = [SwingCatalyst.Test.Unit.TempTest+IRule], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'SwingCatalyst.Test.Unit.TempTest+RuleRegisteredInRoot' can be invoked with the available services and parameters:
Cannot resolve parameter 'System.Func`1[SwingCatalyst.Test.Unit.TempTest+DependencyRegisteredInChildScope] dep' of constructor 'Void .ctor(System.Func`1[SwingCatalyst.Test.Unit.TempTest+DependencyRegisteredInChildScope])'. (See inner exception for details.) (See inner exception for details.) (See inner exception for details.)
  ----> Autofac.Core.DependencyResolutionException : An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = IRule[] (DelegateActivator), Services = [SwingCatalyst.Test.Unit.TempTest+IRule[]], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = ExternallyOwned ---> An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = RuleRegisteredInRoot (ReflectionActivator), Services = [SwingCatalyst.Test.Unit.TempTest+IRule], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'SwingCatalyst.Test.Unit.TempTest+RuleRegisteredInRoot' can be invoked with the available services and parameters:
Cannot resolve parameter 'System.Func`1[SwingCatalyst.Test.Unit.TempTest+DependencyRegisteredInChildScope] dep' of constructor 'Void .ctor(System.Func`1[SwingCatalyst.Test.Unit.TempTest+DependencyRegisteredInChildScope])'. (See inner exception for details.) (See inner exception for details.)
  ----> Autofac.Core.DependencyResolutionException : An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = RuleRegisteredInRoot (ReflectionActivator), Services = [SwingCatalyst.Test.Unit.TempTest+IRule], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'SwingCatalyst.Test.Unit.TempTest+RuleRegisteredInRoot' can be invoked with the available services and parameters:
Cannot resolve parameter 'System.Func`1[SwingCatalyst.Test.Unit.TempTest+DependencyRegisteredInChildScope] dep' of constructor 'Void .ctor(System.Func`1[SwingCatalyst.Test.Unit.TempTest+DependencyRegisteredInChildScope])'. (See inner exception for details.)
  ----> Autofac.Core.DependencyResolutionException : None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'SwingCatalyst.Test.Unit.TempTest+RuleRegisteredInRoot' can be invoked with the available services and parameters:
Cannot resolve parameter 'System.Func`1[SwingCatalyst.Test.Unit.TempTest+DependencyRegisteredInChildScope] dep' of constructor 'Void .ctor(System.Func`1[SwingCatalyst.Test.Unit.TempTest+DependencyRegisteredInChildScope])'.
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at SwingCatalyst.Test.Unit.TempTest.Test(Boolean singleInstance) in C:\Repos\scdesktop\code\build\swingcatalyst\Tests\SwingCatalyst.Test.Unit\TempTest.cs:line 38
--DependencyResolutionException
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
--DependencyResolutionException
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
--DependencyResolutionException
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Autofac.Features.Collections.CollectionRegistrationSource.<>c__DisplayClass0_0.<RegistrationsFor>b__0(IComponentContext c, IEnumerable`1 p)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
--DependencyResolutionException
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
```

**Comment by tillig** [comment]
Super quick off-the-cuff answer since I'm on vacation and only on my phone. @alexmg may have more insight:

It _appears_ you should be able to do this, but what you're doing is forcibly creating a captive dependency. Which is to say:

- The Rules object is a singleton. It lives at the root of the container and will only be activated one time, holding references to anything passed in. Even though you resolve from the child lifetime scope, Rules will get resolved from the root because it's a singleton.
- The rule you've registered is instance per dependency. It gets activated every time you ask for one and will be activated in the scope in which you request it. That may be the container, may be a child scope. But it needs a dependency that isn't registered yet.
- The rule dependency is only registered in a child scope. It's injected with a Func relationship which hard ties it to that scope.

As a singleton you need to be able to satisfy the dependency chain _while resolving from the root container_. For example, you don't want a singleton holding a reference to a request-specific dependency in a web app. What if the singleton took an HttpContext? Would it be right to allow it to hold - forever - the first HttpContext it comes across? No. That's "captive dependency."

That's basically what's happening here - pretend your child lifetime scope is a web request scope. If you could resolve the singleton and satisfy the dependency chain with something that was registered _only_ in the child, it'd incorrectly hold on to the "request scoped" thing forever. No good.

Admittedly the error message doesn't make that clear, but that's what's happening. You've been stopped from making a captive dependency.

When the Rules are _not_ singleton, they get resolved from the child scope, not the container/root, so there's no captive. That's why it works.

**Comment by tillig** [comment]
(So, basically, "unclear error message, but functions as designed.")

**Comment by anjdreas** [comment]
Thanks a bunch, great explanation that makes perfect sense - especially in the HttpContext example.
Maybe the `SingleInstance` docs could benefit from mentioning the concept of "captive dependency"?

**Comment by tillig** [comment]
Good idea. I'll leave this open as a reminder to update the docs.

**Comment by anjdreas** [comment]
I'm drafting up something to discuss around.

**Comment by anjdreas** [comment]
https://github.com/autofac/Documentation/pull/24
