### ISSUE TITLE
NoConstructorsFoundException for valid internal registrations

### ISSUE THREAD

**Issue by 0x084E** [autofac/Autofac#907]
I have a own ConstructorFinder which also searches for non-public constructors and an extension method ``WithNonPublicConstructors`` which calls ``FindConstructorsWith`` with my ConstructorFinder.

This has (partially) stopped working after the 4.7.0 update. If i now call
```
builder.RegisterType<MyType>().AsSelf().WithNonPublicConstructors().SingleInstance();
```
this throws an NoConstructorsFoundException in the call to AsSelf
```
Autofac.Core.Activators.Reflection.NoConstructorsFoundException: No accessible constructors were found for the type 'MyType'.
   at Autofac.Core.Activators.Reflection.DefaultConstructorFinder.GetDefaultPublicConstructors(Type type)
   at Autofac.Core.Activators.Reflection.DefaultConstructorFinder.FindConstructors(Type targetType)
   at Autofac.Core.Activators.Reflection.ReflectionActivator..ctor(Type implementationType, IConstructorFinder constructorFinder, IConstructorSelector constructorSelector, IEnumerable`1 configuredParameters, IEnumerable`1 configuredProperties)
   at Autofac.Builder.ConcreteReflectionActivatorData.get_Activator()
   at Autofac.RegistrationExtensions.AsSelf[TLimit,TConcreteActivatorData](IRegistrationBuilder`3 registration)
   at AutofacModule.Load(ContainerBuilder builder)
   at Autofac.Module.Configure(IComponentRegistry componentRegistry)
   at Autofac.ContainerBuilder.Build(IComponentRegistry componentRegistry, Boolean excludeDefaultModules)
   at Autofac.ContainerBuilder.UpdateRegistry(IComponentRegistry componentRegistry)
   at Autofac.Core.Lifetime.LifetimeScope.CreateScopeRestrictedRegistry(Object tag, Action`1 configurationAction)
   at Autofac.Core.Lifetime.LifetimeScope.BeginLifetimeScope(Object tag, Action`1 configurationAction)
```

If I call WithNonPublicConstructors before AsSelf everything is working as before.

**Comment by tillig** [comment]
This is definitely something we need to look at. The _order_ of those calls is now important. Wow.

Well, I'm glad you have a workaround so you're not stuck. Let us see what we can do. I'm not sure why AsSelf is invoking a constructor finder at registration time. I don't think it should be.

**Comment by tillig** [comment]
I see there's a call to BeginLifetimeScope in there so is this during initial container build? Or is it adding registrations to a child scope? Is there more info you can provide so we can set up an accurate repro test?

**Comment by 0x084E** [comment]
Here is my setup in short. In both cases the first registration will throw while the second won't.

```
        void Test()
        {
            var builder = new ContainerBuilder();
            builder.RegisterType<TestClass>().As<ITest>().AsSelf().FindConstructorsWith(new NonPublicConstructorFinder());
            builder.RegisterType<TestClass>().As<ITest>().FindConstructorsWith(new NonPublicConstructorFinder()).AsSelf();

            var container = builder.Build();

            container.BeginLifetimeScope(
                scopeBuilder =>
                {
                    scopeBuilder.RegisterType<TestClass>().AsSelf().FindConstructorsWith(new NonPublicConstructorFinder());
                    scopeBuilder.RegisterType<TestClass>().FindConstructorsWith(new NonPublicConstructorFinder()).AsSelf();
                });
        }

        public interface ITest
        {
        }

        internal sealed class TestClass : ITest
        {
            internal TestClass()
            {
            }
        }

        private class NonPublicConstructorFinder : DefaultConstructorFinder
        {
            public NonPublicConstructorFinder()
                : base(type => type.GetConstructors(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic))
            {
            }
        }
```

**Comment by ngruson** [comment]
The class ConcreteReflectionActivatorData is getting created during the RegisterType call and passed to the RegistrationBuilder. The base class ReflectionActivatorData is using a DefaultConstructorFinder without any way to pass in a custom constructor finder. 
Not sure of a solution, haven't worked on Autofac before.
But order is now important indeed.

**Comment by tillig** [comment]
Hmm, that bit where AsSelf ignores custom constructor finders sounds like a bug in itself. Good info here, thanks. Definitely needs to be fixed.

**Comment by tillig** [comment]
`AsSelf()`, it turns out, was building a whole temporary reflection-based activator just long enough to get the ultimate limit type (the type of the actual class being registered). The exception was being thrown during the construction of that temporary activator because the activator was eagerly caching the list of available constructors for the limit type. That info isn't actually needed until activation/resolution time, so I switched it to be a lazy cache and the issue no longer appears.

The fix will be in 4.7.1 or later; I want to see if I can get a couple other things in before cutting another drop.

**Comment by tillig** [comment]
@alexandery The problem has the same root cause. Your `AsImplementedInterfaces()` call, internally, is this:

`return registration.As(GetImplementedInterfaces(registration.ActivatorData.Activator.LimitType));`

The root cause on this is the call to `registration.ActivatorData` was eagerly generating the set of available constructors and was ignoring the _later_ call to `FindConstructorsWith()`. This is fixed in 4.7.1, which I just pushed (and may not yet be indexed by NuGet). For a short-term fix, move `FindConstructorsWith` to the front.

**Comment by alexandery** [comment]
@tillig Thanks, I've just re-tested based on the original report here and "fixed" the issue by moving the ctor finder up the chain.

I'll wait for 4.7.1 as there are many components that all follow the same pattern, so changing / rebuilding all of them may be quite time consuming for me at the moment.
