### ISSUE TITLE
4.7.0 breaks FindConstructorsWith() support?

### ISSUE THREAD

**Issue by alexandery** [autofac/Autofac#908]
Hi there,

I've got internal classes with internal ctors, which I used to register with Autofac and resolve with a custom IConstructorFinder implementation. This worked great up until I've upgraded to 4.7.0.

Upgrading to 4.7.0 breaks that - now Autofac throws: 

**Exception**: Autofac.Core.Activators.Reflection.NoConstructorsFoundException
**Message**: No accessible constructors were found for the type 'MyClass'.
**Stack Trace**:
   at Autofac.Core.Activators.Reflection.DefaultConstructorFinder.GetDefaultPublicConstructors(Type type)
   at Autofac.Core.Activators.Reflection.ReflectionActivator..ctor(Type implementationType, IConstructorFinder constructorFinder, IConstructorSelector constructorSelector, IEnumerable`1 configuredParameters, IEnumerable`1 configuredProperties)
   at Autofac.Builder.ConcreteReflectionActivatorData.get_Activator()
   at Autofac.RegistrationExtensions.AsImplementedInterfaces[TLimit,TConcreteActivatorData](IRegistrationBuilder`3 registration)

Autofac version: 4.7.0
.NET Framework Version: 4.6.1

Questions:
1. Is this a bug or by design? If by design, why is there still IConstructorFinder accessible?
2. Why is the breaking change not indicated in your release docs and only the minor version of Autofac is incremented? Issue #773 is there which seems to be the reason for this broken behavior, but it is not indicated as breaking change.
3. Is IConstructorSelector somehow related to this functionality and can be used instead of IConstructorFinder?
4. Last but not least - is there any support for non public ctor or that is not supported any more in any shape or form?

Thank you guys.

**Comment by tillig** [comment]
Duplicate #907
